name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
      - uses: actions/checkout@v5

      - name: Maven Test
        run: mvn Test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
